name: Linting
on: pull_request

jobs:
   prettier:
      name: Prettier
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - uses: actions/setup-node@v4
           with:
              node-version: "lts/iron"
         - uses: pnpm/action-setup@v4
           with:
              version: 10
         - run: pnpm install
         - run: pnpm run lint:prettier:check

   eslint:
      name: Eslint
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - uses: actions/setup-node@v4
           with:
              node-version: "lts/iron"
         - uses: pnpm/action-setup@v4
           with:
              version: 10
         - run: pnpm install
         - run: pnpm run lint:eslint:check

   commitlint:
      name: Commitlint
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
           with:
              fetch-depth: 0
         - uses: actions/setup-node@v4
           with:
              node-version: "lts/iron"
         - uses: pnpm/action-setup@v4
           with:
              version: 10
         - run: pnpm install
         - run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
